django-react연동_오류1
django(backeend)에서 setting.py내부에서 AUTH_USER_MODEL = 'mall.CustomUser' 에서
---------------------------------------
ValueError: The field admin.LogEntry.user was declared with a lazy reference to 'mall.customuser', but app 'mall' doesn't provide model 'customuser'.
--------------------------------------
라는 error발생 ㅠㅠ